// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./app/components/HelloWorld.vue')['default']
    'IconEmojione:flagForIsrael': typeof import('~icons/emojione/flag-for-israel')['default']
    'IconEmojione:flagForUnitedKingdom': typeof import('~icons/emojione/flag-for-united-kingdom')['default']
  }
}

export { }
