// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./app/components/HelloWorld.vue')['default']
    'IconEmojione:flagFor-\xF9s': typeof import('~icons/emojione/flag-for-/x-f9s')['default']
    'IconEmojione:flagForIsrael': typeof import('~icons/emojione/flag-for-israel')['default']
    'IconEmojione:flagForUni': typeof import('~icons/emojione/flag-for-uni')['default']
    'IconEmojione:flagForUnitedKingdom': typeof import('~icons/emojione/flag-for-united-kingdom')['default']
    'IconEmojione:flagForUnitedStates': typeof import('~icons/emojione/flag-for-united-states')['default']
    'IconEmojione:flagForUs': typeof import('~icons/emojione/flag-for-us')['default']
  }
}

export { }
